---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-proxy-prometheus
  labels:
    app: k8s-proxy-prometheus
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-proxy-prometheus
  template:
    metadata:
      labels:
        app: k8s-proxy-prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: k8s-proxy-prometheus
          image: localhost:5000/k8s-proxy-prometheus:latest
          ports:
            - containerPort: 8080  # Application
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60  # Need to wait until the app starts up
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30  # Need to wait until the app is ready
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]  # Wait a few seconds to service-out from the Service before the SIGTERM signal is sent
      terminationGracePeriodSeconds: 120  # Need to wait until the app shuts down

---
kind: Service
apiVersion: v1
metadata:
  name: k8s-proxy-prometheus
  namespace: dev
spec:
  type: NodePort
  selector:
    app: k8s-proxy-prometheus
  ports:
    - name: app
      protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 31000
