---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psystrike
  labels:
    app: psystrike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psystrike
  template:
    metadata:
      labels:
        app: psystrike
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: psystrike
          image: matsumana/psystrike:1.0.0
          ports:
            - containerPort: 8080  # Application
          env:
            - name: TZ
              value: Asia/Tokyo
          #  - name: LOGGING_LEVEL_COM_LINECORP_ARMERIA_LOGGING_ACCESS
          #    value: INFO
          #  - name: LOGGING_LEVEL_INFO_MATSUMANA_PSYSTRIKE
          #    value: DEBUG
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 512Mi
              cpu: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60  # Need to wait until the app starts up
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30  # Need to wait until the app is ready
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]  # Wait a few seconds to service-out from the Service before the SIGTERM signal is sent
      terminationGracePeriodSeconds: 120  # Need to wait until the app shuts down

---
kind: Service
apiVersion: v1
metadata:
  name: psystrike
spec:
  type: NodePort
  selector:
    app: psystrike
  ports:
    - name: app
      protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 31000
