management:
  endpoints:
    enabled-by-default: false   # Disable all of Spring Actuator's endpoints

server:
  ssl:
    enabled: true   # Uses self-signed certificate because no key-store configuration is specified.

armeria:
  ports:
    - port: 8080    # This app serves both HTTP and HTTPS using 8080
      protocol: HTTP
  metrics-path: /metrics
  health-check-path: /healthz

logging:
  level:
    info.matsumana.psystrike: WARN
