management:
  endpoints:
    enabled-by-default: false   # Disable all of Spring Actuator's endpoints

armeria:
  ports:
    # Serve both HTTP and HTTPS(enabled by `server.ssl.enabled=true`) using 8080
    - port: 8080
      protocol: HTTP
    - port: 8080
      protocol: HTTPS
  ssl:
    enabled: true
  metrics-path: /metrics
  health-check-path: /healthz

logging:
  level:
    com.linecorp.armeria.logging.access: WARN   # https://armeria.dev/docs/server-access-log/
    info.matsumana.psystrike: WARN
