management:
  endpoints:
    enabled-by-default: false   # Disable all of Spring Actuator's endpoints

server:
  ssl:
    enabled: true   # Use self-signed certificate

armeria:
  ports:
    - port: 8080    # Serve both HTTP and HTTPS(enabled by `server.ssl.enabled=true`) using 8080
      protocol: HTTP
  metrics-path: /metrics
  health-check-path: /healthz

logging:
  level:
    com.linecorp.armeria.logging.access: WARN   # https://armeria.dev/docs/server-access-log/
    info.matsumana.psystrike: WARN
